### ISSUE TITLE
Tracking localization

### ISSUE THREAD

**Issue by RaulNovelo** [aaaimx/covid19-screening-assistant#8]
Como _administrador_, quiero poder obtener la localización de la persona que contesta el test
para poder saber desde donde esta contestando

## Conditions of satisfaction

- [ ] Leer la documentación de JS para utilizar _geolocation_
- [ ] Obtener _latitud_ y _longitud_
- [ ] Obtener algun otro parámetro reelevante de la sesión
